config/routes.rb
Rails.application.routes.draw do

  get 'transactions/new'

# Root page
  root 'movies#index'

  # Devise user authentication
  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  # Movies
  resources :movies, only: [:show, :index]

  # Shopping Cart
  resource :cart, only: [:show] do
    put 'add/:movie_id', to: 'carts#add', as: :add_to
    put 'remove/:movie_id', to: 'carts#remove', as: :remove_from
  end

  # Payment
  resources :transactions, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
require 'pry'
class Movie < ActiveRecord::Base
  has_many :purchases
  has_many :buyers, through: :purchases

  def poster
    "http://ia.media-imdb.com/images/M/#{poster_url}"
  end

  def imdb
    "http://www.imdb.com/title/#{imdb_id}/"
  end

  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end
  
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :movie
  belongs_to :buyer, class_name: 'User'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :purchases, foreign_key: :buyer_id
  has_many :movies, through: :purchases

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    
# Braintree methods
  FIELDS = [:first_name, :last_name, :phone, :website, :company, :fax, :addresses, :credit_cards, :custom_fields]
  attr_accessor *FIELDS

  def has_payment_info?
    braintree_customer_id
  end

  def with_braintree_data!
    return self unless has_payment_info?
    braintree_data = Braintree::Customer.find(braintree_customer_id)

    FIELDS.each do |field|
      send(:"#{field}=", braintree_data.send(field))
    end
    self
  end

  def default_credit_card
    return unless has_payment_info?
    credit_cards.find { |cc| cc.default? }
  end

  # Cart Methods
  def cart_count
    $redis.scard "cart#{id}"
  end

  def cart_total_price
    total_price = 0
    get_cart_movies.each { |movie| total_price += movie.price }
    total_price
  end

  def get_cart_movies
    cart_ids = $redis.smembers "cart#{id}"
    Movie.find(cart_ids)
  end

  def purchase_cart_movies!
  	get_cart_movies.each { |movie| purchase(movie) }
  	$redis.del "cart#{id}"
  end

  def purchase(movie)
  	movies << movie unless purchase?(movie)
  end

  def purchase?(movie)
  	movies.include?(movie)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  def show
    @cart_movies = current_user.get_cart_movies
  end

  def add
    $redis.sadd current_user_cart, params[:movie_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:movie_id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
    @cart_action = @movie.cart_action current_user.try :id
  end

end

app/controllers/transactions_controller.rb
# require 'pry'
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  # before_action :check_cart!

  def new
  	gon.client_token = generate_client_token
  end

  def create
    unless current_user.has_payment_info?
      @result = Braintree::Transaction.sale(
                  amount: current_user.cart_total_price,
                  payment_method_nonce: params[:payment_method_nonce],
                  customer: {
                    first_name: params[:first_name],
                    last_name: params[:last_name],
                    company: params[:company],
                    email: current_user.email,
                    phone: params[:phone]
                  },
                  options: {
                    store_in_vault: true
                  })
    else
      @result = Braintree::Transaction.sale(
                  amount: current_user.cart_total_price,
                  payment_method_nonce: params[:payment_method_nonce])
    end

    if @result.success?
      current_user.update(braintree_customer_id: @result.transaction.customer_details.id) unless current_user.has_payment_info?
      current_user.purchase_cart_movies!
      redirect_to root_url, notice: "Congraulations! Your transaction was successful!"
    else
      flash[:alert] = "Something went wrong while processing your transaction. Please try again!"
      gon.client_token = generate_client_token
      render :new
    end
  end
  
  private
  
  def generate_client_token
    if current_user.has_payment_info?
      Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
    else
      Braintree::ClientToken.generate
    end
  end

#not needed anymore
  # def check_cart!
  # 	if current_user.get_cart_movies.blank?
  # 		redirect_to root_url, alert: "Please add a movie to your cart!"
  # 	end
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/carts/show.html.erb
<div id="mycart" class="small-10 small-centered medium-8 large-8 column">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> movies!</p>
  </div>

  <% @cart_movies.each do |movie|%>
  <div data-equalizer class="cart-movie large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to movie do%>
        <%=image_tag movie.poster, class: "radius-l1"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= movie.title %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(movie)} do%>
        <i class="fi-x right"></i>
      <%end%>
      <h4 class="scale">$ <%= movie.price %></h4>
    </div>
  </div>
  <%end%>
  <%=link_to "Checkout", new_transaction_path, class: "button" unless current_user.get_cart_movies.blank?%>
</div>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row full-width">

    <div class="small-12 medium-3 large-4 columns">
      <i class="fi-html5"></i>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit impedit consequuntur at! Amet sed itaque nostrum, distinctio eveniet odio, id ipsam fuga quam minima cumque nobis veniam voluptates deserunt!</p>
    </div>
    <div class="small-6 medium-2 medium-offset-2 large-2 columns">
      <h4>Work With Me</h4>
      <ul class="footer-links">
        <li><a href="#">What I Do</a></li>
        <li><a href="#">Pricing</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">FAQ's</a></li>
      <ul>
    </div>
    <div class="small-6 medium-4 large-2 columns">
      <h4>Follow Me</h4>
      <ul class="footer-links">
        <li><a href="https://github.com/jakegibs617">GitHub</a></li>
        <li><a href="https://www.linkedin.com/in/jakegibs617">LinkedIn</a></li>
        <li><a href="http://anotherlauncher.tumblr.com/">Blog</a></li>
      <ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="header columns">
    <h1 class="headline ">Jacob Giberson  <small>2017</small></h1>


    <ul class="header-subnav ">
      <li>
          <h1>
            <a href="/">
              <i class="fi-play-video"></i> Home
            </a>
          </h1>
      </li>
        <%if signed_in?%>
          <li>
            <%= link_to cart_path do%>
              <i class="fi-shopping-cart"></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%=link_to "Register", new_user_registration_path%></li>
          <li><%=link_to "Login", new_user_session_path%></li>
        <%end%>
    </ul>

</header>

app/views/layouts/_slider.html.erb
<div class="slideshow hide-for-small-only hide-for-medium-only">

<!-- slick slier of movies -->
  <% @movies.each do |m| %>
      <div> <%= link_to image_tag(m.poster, title: m.title), movie_path(m) %> </div>
  <% end %>

</div>


<script type="text/javascript">
	$('.slideshow').slick({
	 slidesToShow: 6,
	  slidesToScroll: 1,
	  autoplay: true,
	  autoplaySpeed: 5000,
	});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Rails Ecommerce" %></title>
    <%= favicon_link_tag 'favicon.ico' %>

    <%= include_gon %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>


    <%= csrf_meta_tags %>


  </head>

<body>

  <%=render partial: "layouts/header" unless current_page?("/")%>

  <%=render partial: "layouts/alerts" unless current_page?("/")%>


  <div id="main-content" class="row full-min-height">
    <%= yield %>
  </div>
  <%=render partial: "layouts/footer" unless current_page?("/")%>
</body>


</html>

app/views/movies/index.html.erb
<header class="header " style="width:100vw; margin-left:-10%; background:none;">
  <!-- <div class="row "> -->
    <h1 class="headline ">Jacob Giberson  <small>2017</small></h1>
  <!-- </div> -->
  <div class="row">

    <ul class="header-subnav ">
      <li>
          <h1>
            <a href="/">
              <i class="fi-play-video"></i> Home
            </a>
          </h1>
      </li>
        <%if signed_in?%>
          <li>
            <%= link_to cart_path do%>
              <i class="fi-shopping-cart"></i> My Cart (<span class="cart-count"><%=current_user.cart_count%></span>)
            <%end%>
          </li>
          <li><%=link_to current_user.email, edit_user_registration_path%></li>
          <li><%=link_to "Logout", destroy_user_session_path, method: :delete%></li>
        <%else%>
          <li><%=link_to "Register", new_user_registration_path%></li>
          <li><%=link_to "Login", new_user_session_path%></li>
        <%end%>
    </ul>
  </div>

</header>

<div class="row">
  <div class="small-offset-2 columns">

    <%= render "layouts/slider" %>
  </div>
</div>

<br>

<div class="off-canvas-wrapper">
      <%if notice.present? || alert.present? %>
      <div class="row">
        <%is_alert = alert.present? ? "alert" : ""%>
          <div data-alert class="alert-box <%=is_alert%>">
            <%=notice || alert%>
            <a href="#" class="close">&times;</a>
          </div>
      </div>
    <%end%>
      <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>

        <div class="off-canvas position-left reveal-for-large" id="my-info" data-off-canvas data-position="left">
          <div class="row column">
            <br>
            <img class="thumbnail" src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAf7AAAAJDkwNjdlZDg4LTNkNjEtNDM4MC1hYTdiLWVmZWI3YWY5MGQxMA.jpg">
            <h5>Jacob Giberson</h5>
            <p>This is where I will eventually say a little bit about who I am</p>
          </div>
        </div>

        <div class="off-canvas-content" data-off-canvas-content>
          <div class="title-bar hide-for-large">
            <div class="title-bar-left">
              <button class="menu-icon" type="button" data-open="my-info"></button>
              <span class="title-bar-title">Jacob Giberson</span>
            </div>
          </div>
          <div >
            <div class="row column">
              <h1>Hello! This is one of my portfolios.</h1>
              <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus luctus urna sed urna ultricies ac tempor dui sagittis. In condimentum facilisis porta. Sed nec diam eu diam mattis viverra. Nulla fringilla.</p>
            </div>
          </div>
          <div class="row small-up-2 medium-up-3 large-up-4">
            <% @movies.each do |movie| %>
              <div class="column ">
                <%= link_to movie, class: "poster " do %>
                  <%= image_tag movie.poster %>
                <% end %>
                <h5 class="movie-info ell glassy-bg padmy padlx"><%= movie.title %> <span>(<%= movie.release_year %>)</span></h5>
                <p class="left price label movie-label radius">$ <%= movie.price %></p>
                <%= link_to movie.imdb, class: "right imdb-image" do %>
                  <%= image_tag ("imdb_logo.png") %>
                <% end %>
              </div>
            <% end %>
          </div>

          <hr>

          <div class="row">
            <div class="medium-6 columns">
              <h3>Contact Me</h3>
              <p>Vivamus hendrerit arcu sed erat molestie vehicula. Sed auctor neque eu tellus rhoncus ut eleifend nibh porttitor. Ut in nulla enim. Phasellus molestie magna non est bibendum non venenatis nisl tempor. Suspendisse dictum feugiat nisl ut dapibus. Mauris iaculis porttitor.</p>
              <ul class="menu">
                <li><a href="https://github.com/jakegibs617">Github</a></li>
                <li><a href="https://www.linkedin.com/in/jakegibs617">LinkedIn</a></li>
                <li><a href="http://anotherlauncher.tumblr.com/">Blog</a></li>
              </ul>
            </div>
            <div class="medium-6 columns">
              <label>Name
                <input type="text" placeholder="Name">
              </label>
              <label>Email
                <input type="text" placeholder="Email">
              </label>
              <label>
                Message
                <textarea placeholder="hello world"></textarea>
              </label>
              <input type="submit" class="button expanded" value="Submit">
            </div>
          </div>
        </div>
      </div>
    </div>

<footer class="footer" style="width:100vw; background:none;">
  <div class="row ">

    <div class="small-12 medium-3 medium-offset-2 large-4 columns">
      <i class="fi-html5"></i>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fugit impedit consequuntur at! Amet sed itaque nostrum, distinctio eveniet odio, id ipsam fuga quam minima cumque nobis veniam voluptates deserunt!</p>
    </div>
    <div class="small-6 medium-2 medium-offset-1 large-2 columns">
      <h4>Work With Me</h4>
      <ul class="footer-links">
        <li><a href="#">What I Do</a></li>
        <li><a href="#">Pricing</a></li>
        <li><a href="#">Events</a></li>
        <li><a href="#">Blog</a></li>
        <li><a href="#">FAQ's</a></li>
      <ul>
    </div>
    <div class="small-6 medium-4 large-2 columns">
      <h4>Follow Me</h4>
      <ul class="footer-links">
        <li><a href="https://github.com/jakegibs617">GitHub</a></li>
        <li><a href="https://www.linkedin.com/in/jakegibs617">LinkedIn</a></li>
        <li><a href="http://anotherlauncher.tumblr.com/">Blog</a></li>
      <ul>
    </div>
  </div>
</footer>

app/views/movies/show.html.erb
<div class="large-3 small-12 column">
  <%=image_tag @movie.poster%>
</div>
<div class="large-9 small-12 column">
  <h3>
    <%= @movie.title %>
    (<%= @movie.release_year %>)
    <%=link_to @movie.imdb, id: "imdb-logo-show" do%>
      <%=image_tag asset_path("imdb_logo.png")%>
    <%end%>
  </h3>

    <p class="label movie-label radius mb1">
      <%= (current_user && current_user.purchase?(@movie)) ? "Purchased" : "$#{@movie.price}" %>
    </p>

  <p><%= @movie.description %></p>

  <%if signed_in?%>
    <%if current_user.purchase? @movie %>
      <div class="flex-video">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @movie.video_url %>" frameborder="0" allowfullscreen></iframe>

      </div>
    <%else%>
      <%=link_to "", class: "button", data: {target: @cart_action, addUrl: add_to_cart_path(@movie), removeUrl: remove_from_cart_path(@movie)} do%>
        <i class="fi-shopping-cart"></i>
        <span><%=@cart_action%></span> Cart
      <%end%>
    <%end%>
  <%end%>
</div>

app/views/transactions/_customer_form.html.erb
<p>Please enter your personal info:</p>
<div class="mb1">
  <%= text_field_tag :first_name, "",placeholder: "First Name", class: "radius" %>
</div>
<div class="mb1">
  <%= text_field_tag :last_name, "",placeholder: "Last Name", class: "radius" %>
</div>
<div class="mb1">
  <%= text_field_tag :company, "",placeholder: "Company", class: "radius" %>
</div>
<div class="mb1">
  <%= text_field_tag :phone, "",placeholder: "Phone", class: "radius" %>
</div>

app/views/transactions/new.html.erb
<div class="form-container radius-box glassy-bg small-10 small-centered medium-8 large-6 columns">
  <h2 class="mbs">New Transaction</h2>
	<%= form_tag transactions_path do%>
	  <%= render 'customer_form' unless current_user.has_payment_info? %>
	  <p>Please enter your payment details:</p>
	  <div id="dropin"></div>
	  <%=submit_tag "Pay #{current_user.cart_total_price}$", class: "button mt1" %>
	<%end%>
</div>


<script src="https://js.braintreegateway.com/v2/braintree.js"></script>